import { articleUrl, PUBLIC_SITE_ORIGIN, type PublicResourceArticle } from './resources';

export interface GlossaryTerm {
  term: string;
  category: string;
  summary: string;
  officeUse: string;
  relatedSlug?: string;
}

export const glossaryTerms: GlossaryTerm[] = [
  {
    term: 'الرادار اليومي',
    category: 'تشغيل المكتب',
    summary: 'قائمة انتباه يومية تعرض ما يحتاج قراراً أو متابعة: دفعات متأخرة، عقود قريبة الانتهاء، أو فجوات تشغيلية.',
    officeUse: 'يستخدمه المدير في بداية اليوم لترتيب الأولويات قبل فتح الرسائل والملفات المتفرقة.',
    relatedSlug: 'real-estate-office-operating-system',
  },
  {
    term: 'المتابعة',
    category: 'تشغيل المكتب',
    summary: 'سجل عمل له حالة ومسؤول ومصدر، يربط الإشارة التشغيلية بالفعل المطلوب حتى الإغلاق.',
    officeUse: 'تحول الدفعة المتأخرة أو الملاحظة أو طلب العميل إلى إجراء واضح لا يعتمد على ذاكرة شخص واحد.',
    relatedSlug: 'tenant-follow-up-policy',
  },
  {
    term: 'أعمار الديون',
    category: 'التحصيل',
    summary: 'تقسيم المتأخرات حسب مدة التأخر، مثل ١-٣٠ و٣١-٦٠ و٦١-٩٠ يوماً.',
    officeUse: 'يساعد المكتب على معرفة أين يبدأ التحصيل، وما الذي يحتاج تصعيداً أو مراجعة عقد.',
    relatedSlug: 'rent-collection-aging-guide',
  },
  {
    term: 'الاستحقاق',
    category: 'التحصيل',
    summary: 'المبلغ المتوقع دفعه في تاريخ محدد وفق العقد أو جدول الدفعات.',
    officeUse: 'يفصل بين ما يجب أن يُدفع وما دُفع فعلاً، وهذا أساس تقارير التحصيل.',
    relatedSlug: 'real-estate-reports-for-decisions',
  },
  {
    term: 'التحصيل',
    category: 'التحصيل',
    summary: 'تسجيل الدفعة الفعلية التي دخلت للمكتب أو حساب المالك، وربطها بالاستحقاق الصحيح.',
    officeUse: 'يمنع بقاء المبلغ مجرد وعد أو رسالة، ويجعل التقرير المالي قابلاً للمراجعة.',
    relatedSlug: 'rent-collection-aging-guide',
  },
  {
    term: 'دفتر المكتب',
    category: 'دفتر المكتب',
    summary: 'دفتر مستقل لإيرادات ومصروفات والتزامات المكتب كجهة تشغيل، لا للعقار نفسه.',
    officeUse: 'يفصل رواتب المكتب واشتراكاته ومصروفاته عن حركة الإيجارات والعقارات.',
    relatedSlug: 'office-ledger-vs-property-ledger',
  },
  {
    term: 'مصروف مكتبي',
    category: 'دفتر المكتب',
    summary: 'مصروف يخدم المكتب عموماً ولا يرتبط بعقار أو وحدة بعينها.',
    officeUse: 'يساعد على قراءة تكلفة تشغيل المكتب دون خلطها بمصاريف العقارات.',
    relatedSlug: 'office-expense-categories-guide',
  },
  {
    term: 'التزام مكتبي',
    category: 'دفتر المكتب',
    summary: 'مبلغ متكرر أو مؤجل على المكتب نفسه مثل اشتراك أو خدمة أو دفعة تشغيلية.',
    officeUse: 'يمنع نسيان مصروفات المكتب الدورية التي لا تظهر داخل عقود الإيجار.',
    relatedSlug: 'office-expense-categories-guide',
  },
  {
    term: 'عقد إيجار PDF',
    category: 'عقود الإيجار',
    summary: 'ملف عقد يمكن استخدامه كمصدر بداية لاستخراج بيانات أساسية قبل المراجعة البشرية.',
    officeUse: 'يقلل الإدخال اليدوي مع إبقاء مسؤولية التأكيد والمراجعة على المستخدم.',
    relatedSlug: 'ejar-contract-import-review',
  },
  {
    term: 'جدول الاستحقاقات',
    category: 'عقود الإيجار',
    summary: 'قائمة الدفعات المتوقعة للعقد، بتواريخها ومبالغها وحالتها.',
    officeUse: 'هو الرابط بين العقد والتحصيل والتقارير، وأي خطأ فيه يظهر في بقية الدورة.',
    relatedSlug: 'ejar-contract-import-review',
  },
  {
    term: 'تجديد العقد',
    category: 'عقود الإيجار',
    summary: 'قرار تشغيلي قبل انتهاء العقد: تمديد، تعديل، أو إنهاء وفق سياق المستأجر والعقار.',
    officeUse: 'ينبغي أن يبدأ قبل تاريخ الانتهاء بفترة كافية حتى لا يتحول إلى مفاجأة تشغيلية.',
    relatedSlug: 'lease-renewal-workflow',
  },
  {
    term: 'ملف المصدر',
    category: 'المستندات',
    summary: 'المستند الأصلي الذي جاءت منه بيانات العقد أو الملاحظة أو الإجراء.',
    officeUse: 'يحمي المكتب عند المراجعة أو النزاع لأن السجل يعود إلى مستند واضح.',
    relatedSlug: 'real-estate-document-archive-guide',
  },
  {
    term: 'أرشيف المستندات',
    category: 'المستندات',
    summary: 'تنظيم ملفات العقود والخطابات والمرفقات بحيث تكون قابلة للبحث والرجوع.',
    officeUse: 'يقلل ضياع الملفات بين الأجهزة والمحادثات، ويربط المستند بسياقه التشغيلي.',
    relatedSlug: 'real-estate-document-archive-guide',
  },
  {
    term: 'ذاكرة المكتب',
    category: 'الذاكرة',
    summary: 'سجل معرفة تشغيلية يحفظ الملاحظات والسياقات المهمة عن العملاء والعقارات والمتابعات.',
    officeUse: 'ينقل المعرفة من ذاكرة الأفراد إلى أصل تشغيلي داخل المكتب.',
    relatedSlug: 'real-estate-office-memory',
  },
  {
    term: 'ملاحظة مشتركة',
    category: 'الذاكرة',
    summary: 'ملاحظة يمكن للفريق الاستفادة منها لأنها تؤثر على خدمة العميل أو متابعة العقار.',
    officeUse: 'تستخدم عند وجود سياق يجب أن يعرفه أكثر من موظف، مثل تفضيل تواصل أو إجراء خاص.',
    relatedSlug: 'real-estate-office-memory',
  },
  {
    term: 'تقرير التدفق النقدي',
    category: 'التقارير',
    summary: 'تقرير يوضح النقد الداخل والخارج فعلياً خلال فترة محددة.',
    officeUse: 'يساعد المالك أو المدير على فهم السيولة الفعلية لا مجرد الاستحقاقات المتوقعة.',
    relatedSlug: 'real-estate-reports-for-decisions',
  },
  {
    term: 'نسبة التحصيل',
    category: 'التقارير',
    summary: 'مؤشر يقارن المبالغ المحصلة بالمبالغ المستحقة خلال فترة أو نطاق معين.',
    officeUse: 'يحتاج قراءة مع أعمار الديون حتى لا تخفي النسبة الجيدة ديوناً قديمة.',
    relatedSlug: 'real-estate-reports-for-decisions',
  },
  {
    term: 'تقرير المالك الشهري',
    category: 'التقارير',
    summary: 'ملخص دوري يشرح للمالك ما حدث في العقار: تحصيل، مصروفات، متأخرات، وملاحظات مهمة.',
    officeUse: 'يجعل التواصل مع المالك مبنياً على سجل واضح بدلاً من رسائل متفرقة.',
    relatedSlug: 'property-owner-monthly-report',
  },
  {
    term: 'دورة التشغيل',
    category: 'تشغيل المكتب',
    summary: 'تسلسل العمل اليومي من ظهور الإشارة إلى فتح المتابعة ثم تسجيل القرار أو الإغلاق.',
    officeUse: 'تساعد المدير على معرفة أين يبدأ اليوم وأين تنتهي كل مهمة مهمة.',
    relatedSlug: 'real-estate-office-management-saudi-arabia-guide',
  },
  {
    term: 'إشارة تشغيلية',
    category: 'تشغيل المكتب',
    summary: 'حدث أو حالة تستحق انتباه المكتب مثل دفعة متأخرة أو عقد قريب الانتهاء.',
    officeUse: 'تتحول إلى متابعة إذا احتاجت إجراءً أو مسؤولاً واضحاً.',
    relatedSlug: 'real-estate-office-operating-system',
  },
  {
    term: 'مسؤول المتابعة',
    category: 'تشغيل المكتب',
    summary: 'الشخص المكلف بإغلاق متابعة محددة أو تحديثها حتى لا تبقى معلقة.',
    officeUse: 'يمنع ضياع المهام بين الفريق ويجعل المسؤولية واضحة.',
    relatedSlug: 'tenant-follow-up-policy',
  },
  {
    term: 'حالة المتابعة',
    category: 'تشغيل المكتب',
    summary: 'وصف مختصر لموقع المتابعة في دورة العمل: مفتوحة، قيد الانتظار، مغلقة، أو تحتاج تصعيداً.',
    officeUse: 'تساعد الفريق على فرز ما يحتاج إجراءً وما يمكن مراجعته لاحقاً.',
    relatedSlug: 'tenant-follow-up-policy',
  },
  {
    term: 'إغلاق المتابعة',
    category: 'تشغيل المكتب',
    summary: 'تسجيل سبب انتهاء المتابعة بعد تحصيل أو قرار أو انتفاء الحاجة.',
    officeUse: 'يمنع تراكم المتابعات المفتوحة بلا معنى.',
    relatedSlug: 'rent-collection-arrears-complete-guide',
  },
  {
    term: 'دفعة جزئية',
    category: 'التحصيل',
    summary: 'مبلغ مدفوع لا يغطي كامل الاستحقاق المطلوب.',
    officeUse: 'تحتاج ربطاً واضحاً بالاستحقاق حتى لا يظهر التقرير كأن الدفعة اكتملت.',
    relatedSlug: 'rent-collection-arrears-complete-guide',
  },
  {
    term: 'وعد بالدفع',
    category: 'التحصيل',
    summary: 'تعهد من المستأجر أو العميل بسداد مبلغ في وقت لاحق، لكنه ليس تحصيلاً فعلياً.',
    officeUse: 'يسجل كمتابعة لها تاريخ مراجعة، ولا يضاف إلى التحصيل إلا عند دخول الدفعة.',
    relatedSlug: 'rent-collection-arrears-complete-guide',
  },
  {
    term: 'دفعة متأخرة',
    category: 'التحصيل',
    summary: 'استحقاق لم يسدد بعد مرور تاريخ الدفع المحدد.',
    officeUse: 'تظهر في الرادار أو تقرير أعمار الديون لتحديد أولوية المتابعة.',
    relatedSlug: 'rent-collection-aging-guide',
  },
  {
    term: 'متأخرات قديمة',
    category: 'التحصيل',
    summary: 'مبالغ متأخرة لفترة طويلة وتحتاج مراجعة أو تصعيداً أو قراراً إدارياً.',
    officeUse: 'تمنع المكتب من الاكتفاء بنسبة تحصيل جيدة تخفي ديوناً متراكمة.',
    relatedSlug: 'rent-collection-arrears-complete-guide',
  },
  {
    term: 'سياسة التحصيل',
    category: 'التحصيل',
    summary: 'طريقة داخلية تحدد مراحل متابعة المستحقات والمتأخرات وما يجب تسجيله.',
    officeUse: 'توحّد لغة الفريق وتمنع التواصل المتكرر أو المتناقض مع المستأجرين.',
    relatedSlug: 'rent-collection-arrears-complete-guide',
  },
  {
    term: 'تصعيد التحصيل',
    category: 'التحصيل',
    summary: 'نقل حالة متأخرة من متابعة عادية إلى مراجعة إدارية أو إجراء أعلى.',
    officeUse: 'يستخدم عند تكرار الوعود أو طول مدة التأخر أو وجود نزاع يحتاج قراراً.',
    relatedSlug: 'rent-collection-arrears-complete-guide',
  },
  {
    term: 'قيمة الإيجار',
    category: 'عقود الإيجار',
    summary: 'المبلغ المتفق عليه في العقد والذي تبنى عليه الاستحقاقات والتقارير.',
    officeUse: 'أي خطأ فيها ينتقل مباشرة إلى جدول الدفعات والتحصيل.',
    relatedSlug: 'lease-contracts-obligations-complete-guide',
  },
  {
    term: 'تكرار الدفع',
    category: 'عقود الإيجار',
    summary: 'طريقة تقسيم الإيجار زمنياً: شهري، ربع سنوي، نصف سنوي، أو سنوي.',
    officeUse: 'يحدد عدد الاستحقاقات وتواريخها داخل العقد.',
    relatedSlug: 'lease-contracts-obligations-complete-guide',
  },
  {
    term: 'تاريخ بداية العقد',
    category: 'عقود الإيجار',
    summary: 'التاريخ الذي تبدأ منه مدة العقد وحساب الاستحقاقات.',
    officeUse: 'يجب مراجعته قبل اعتماد جدول الدفعات لأنه يؤثر على كل تواريخ التحصيل.',
    relatedSlug: 'lease-contracts-obligations-complete-guide',
  },
  {
    term: 'تاريخ نهاية العقد',
    category: 'عقود الإيجار',
    summary: 'التاريخ الذي تنتهي عنده مدة العقد أو يبدأ قبله مسار التجديد.',
    officeUse: 'يساعد الرادار على إظهار العقود القريبة من الانتهاء قبل أن تصبح أزمة.',
    relatedSlug: 'lease-renewal-workflow',
  },
  {
    term: 'مراجعة بشرية',
    category: 'عقود الإيجار',
    summary: 'تأكيد المستخدم للبيانات المهمة قبل اعتماد العقد أو جدول الاستحقاقات.',
    officeUse: 'تحمي المكتب من أخطاء استخراج أو إدخال تؤثر على التحصيل والتقارير.',
    relatedSlug: 'ejar-contract-import-review',
  },
  {
    term: 'استحقاق قادم',
    category: 'عقود الإيجار',
    summary: 'دفعة لم يحل موعدها بعد لكنها تظهر قريباً في الرادار أو التقارير.',
    officeUse: 'تساعد المكتب على التذكير المبكر بدلاً من الانتظار حتى التأخر.',
    relatedSlug: 'daily-real-estate-office-checklist',
  },
  {
    term: 'مصروف عقار',
    category: 'دفتر المكتب',
    summary: 'مصروف مرتبط بعقار أو وحدة محددة وليس بتشغيل المكتب عموماً.',
    officeUse: 'يفصل أداء العقار عن تكلفة تشغيل المكتب.',
    relatedSlug: 'office-ledger-vs-property-ledger',
  },
  {
    term: 'إيراد مكتبي',
    category: 'دفتر المكتب',
    summary: 'دخل يخص المكتب ككيان تشغيل وليس دفعة إيجار مرتبطة بعقد محدد.',
    officeUse: 'يساعد على قراءة دخل المكتب بعيداً عن تحصيل العقارات.',
    relatedSlug: 'office-ledger-vs-property-ledger',
  },
  {
    term: 'تصنيف المصروف',
    category: 'دفتر المكتب',
    summary: 'وضع المصروف في فئة تساعد على فهم تكلفة التشغيل مثل رواتب أو اشتراكات أو تسويق.',
    officeUse: 'يمنع تراكم المصروفات في خانة أخرى بلا معنى إداري.',
    relatedSlug: 'office-expense-categories-guide',
  },
  {
    term: 'مصروف متكرر',
    category: 'دفتر المكتب',
    summary: 'تكلفة تظهر بشكل دوري مثل اشتراك نظام أو خدمة أو إيجار مقر.',
    officeUse: 'تحتاج متابعة مسبقة حتى لا تفاجئ التدفق النقدي للمكتب.',
    relatedSlug: 'office-expense-categories-guide',
  },
  {
    term: 'إغلاق شهري',
    category: 'دفتر المكتب',
    summary: 'مراجعة شهرية للمصروفات والالتزامات والإيرادات قبل اعتماد صورة التشغيل.',
    officeUse: 'يكشف البنود غير المصنفة والالتزامات القادمة وتغير تكلفة التشغيل.',
    relatedSlug: 'office-expense-categories-guide',
  },
  {
    term: 'مرفق تشغيلي',
    category: 'المستندات',
    summary: 'ملف يدعم إجراءً أو متابعة مثل إثبات دفع أو خطاب أو صورة مستند.',
    officeUse: 'يربط الدليل بالسجل الذي يخصه بدلاً من حفظه في مجلد عام.',
    relatedSlug: 'real-estate-document-archive-guide',
  },
  {
    term: 'إثبات دفع',
    category: 'المستندات',
    summary: 'مستند أو صورة تثبت دفع مبلغ مرتبط باستحقاق أو مصروف.',
    officeUse: 'يساعد على مراجعة التحصيل أو المصروف عند وجود سؤال أو خلاف.',
    relatedSlug: 'real-estate-document-archive-guide',
  },
  {
    term: 'تسمية الملفات',
    category: 'المستندات',
    summary: 'طريقة موحدة لكتابة اسم الملف بحيث يحمل نوع المستند والطرف أو العقار والتاريخ.',
    officeUse: 'تجعل البحث أسهل وتقلل أسماء مثل scan وfinal التي تفقد معناها سريعاً.',
    relatedSlug: 'real-estate-document-archive-guide',
  },
  {
    term: 'صلاحيات المستند',
    category: 'المستندات',
    summary: 'تحديد من يستطيع رؤية المستند أو استخدامه داخل المكتب.',
    officeUse: 'يحمي الملفات الحساسة ويمنع مشاركة ما لا يحتاجه كل الفريق.',
    relatedSlug: 'real-estate-document-archive-guide',
  },
  {
    term: 'سياق العميل',
    category: 'الذاكرة',
    summary: 'معلومات مختصرة تؤثر على طريقة التعامل مع عميل أو مستأجر.',
    officeUse: 'تساعد الموظف على التواصل بوعي دون الرجوع إلى رسائل قديمة.',
    relatedSlug: 'real-estate-office-memory',
  },
  {
    term: 'تفضيل التواصل',
    category: 'الذاكرة',
    summary: 'وقت أو وسيلة يفضلها العميل للتواصل معه.',
    officeUse: 'يحسن تجربة العميل ويقلل محاولات التواصل غير المناسبة.',
    relatedSlug: 'real-estate-office-memory',
  },
  {
    term: 'معلومة تشغيلية',
    category: 'الذاكرة',
    summary: 'تفصيل صغير يؤثر على إجراء لاحق مثل عادة دفع أو شرط داخلي أو ملاحظة عن عقار.',
    officeUse: 'تسجل عندما يكون لها أثر على قرار أو متابعة وليس لمجرد الأرشفة.',
    relatedSlug: 'real-estate-office-memory',
  },
  {
    term: 'تاريخ آخر تحديث',
    category: 'الذاكرة',
    summary: 'آخر وقت تغيرت فيه ملاحظة أو متابعة أو سجل مهم.',
    officeUse: 'يساعد المدير على معرفة السجلات التي قد تحتاج مراجعة.',
    relatedSlug: 'real-estate-office-memory',
  },
  {
    term: 'ملخص تنفيذي',
    category: 'التقارير',
    summary: 'خلاصة قصيرة في بداية التقرير تعرض أهم الأرقام والملاحظات والقرارات المطلوبة.',
    officeUse: 'يساعد المالك أو المدير على فهم الصورة قبل قراءة التفاصيل.',
    relatedSlug: 'property-owner-monthly-report',
  },
  {
    term: 'المحصل فعلاً',
    category: 'التقارير',
    summary: 'المبلغ الذي دخل وسُجل كدفعة حقيقية خلال فترة التقرير.',
    officeUse: 'يميز النقد الفعلي عن الاستحقاقات أو الوعود.',
    relatedSlug: 'real-estate-reports-for-decisions',
  },
  {
    term: 'المستحق خلال الفترة',
    category: 'التقارير',
    summary: 'إجمالي الدفعات المتوقع تحصيلها خلال نطاق زمني محدد.',
    officeUse: 'يستخدم لمقارنة المتوقع بالمحصل وقراءة فجوة التحصيل.',
    relatedSlug: 'real-estate-reports-for-decisions',
  },
  {
    term: 'فجوة التحصيل',
    category: 'التقارير',
    summary: 'الفرق بين ما كان يجب تحصيله وما تم تحصيله فعلاً.',
    officeUse: 'تساعد على معرفة هل المشكلة في التأخر أم في التسجيل أم في جودة المتابعة.',
    relatedSlug: 'rent-collection-arrears-complete-guide',
  },
  {
    term: 'تقرير العقار',
    category: 'التقارير',
    summary: 'ملخص أداء عقار محدد من حيث التحصيل والمصروفات والمتأخرات والملاحظات.',
    officeUse: 'يساعد على مقارنة أداء العقارات واتخاذ قرار إداري واضح.',
    relatedSlug: 'property-owner-monthly-report',
  },
  {
    term: 'قرار إداري',
    category: 'التقارير',
    summary: 'إجراء أو توجيه ينتج عن قراءة تقرير أو متابعة، مثل تصعيد أو تجديد أو مراجعة عقد.',
    officeUse: 'يربط التقرير بالفعل بدلاً من أن يبقى مجرد أرقام.',
    relatedSlug: 'real-estate-reports-for-decisions',
  },
  {
    term: 'ملف إكسل تشغيلي',
    category: 'تشغيل المكتب',
    summary: 'جدول يستخدمه المكتب لإدارة جزء من العمل اليومي مثل العقارات أو التحصيل أو المصروفات.',
    officeUse: 'يصلح كبداية، لكنه يحتاج ضبطاً عندما يصبح هو المصدر الوحيد للعقود والمتابعات والتقارير.',
    relatedSlug: 'excel-real-estate-office-management-guide',
  },
  {
    term: 'سجل الإيجارات',
    category: 'التقارير',
    summary: 'جدول يجمع الوحدات والمستأجرين والعقود وقيم الإيجار وحالة الإشغال في صورة واحدة.',
    officeUse: 'يساعد على فهم الدخل المتوقع وحالة العقود، ويقابل مفهوم rent roll في الأدبيات العقارية.',
    relatedSlug: 'excel-real-estate-office-management-guide',
  },
  {
    term: 'نسخة الملف المعتمدة',
    category: 'تشغيل المكتب',
    summary: 'النسخة التي يعتمدها المكتب كمصدر صحيح عند وجود عدة ملفات أو نسخ متداولة.',
    officeUse: 'تمنع تضارب الأرقام قبل تنظيف البيانات أو نقلها إلى نظام.',
    relatedSlug: 'excel-real-estate-office-management-guide',
  },
  {
    term: 'ترحيل البيانات',
    category: 'تشغيل المكتب',
    summary: 'نقل بيانات العقارات والعقود والتحصيل من ملفات قديمة إلى نظام أو بنية أكثر تنظيماً.',
    officeUse: 'يجب أن يبدأ بالعقود النشطة والمتأخرات والحقول المهمة بدلاً من الأرشيف الكامل.',
    relatedSlug: 'excel-real-estate-office-management-guide',
  },
  {
    term: 'تنظيف البيانات',
    category: 'تشغيل المكتب',
    summary: 'مراجعة الأعمدة والقيم والتواريخ والحالات قبل الاعتماد أو النقل.',
    officeUse: 'يمنع نقل أخطاء الإكسل نفسها إلى التقرير أو النظام الجديد.',
    relatedSlug: 'excel-real-estate-office-management-guide',
  },
];

export function glossaryJsonLd(articles: PublicResourceArticle[]) {
  return [
    {
      '@context': 'https://schema.org',
      '@type': 'DefinedTermSet',
      name: 'قاموس قيد العقار التشغيلي',
      inLanguage: 'ar-SA',
      url: `${PUBLIC_SITE_ORIGIN}/resources/terms`,
      hasDefinedTerm: glossaryTerms.map((item) => ({
        '@type': 'DefinedTerm',
        name: item.term,
        description: item.summary,
        inDefinedTermSet: `${PUBLIC_SITE_ORIGIN}/resources/terms`,
      })),
    },
    {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      name: 'مصطلحات مرتبطة بأدلة قيد العقار',
      itemListElement: glossaryTerms
        .filter((item) => item.relatedSlug)
        .map((item, index) => {
          const article = articles.find((candidate) => candidate.slug === item.relatedSlug);
          return {
            '@type': 'ListItem',
            position: index + 1,
            name: item.term,
            url: article ? `${PUBLIC_SITE_ORIGIN}${articleUrl(article)}` : `${PUBLIC_SITE_ORIGIN}/resources/terms`,
          };
        }),
    },
  ];
}
